# Generated by Django 4.0.5 on 2022-06-10 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('language', models.CharField(choices=[('ENGLISH', 'English'), ('FRENCH', 'French'), ('SPANISH', 'Spanish'), ('MANDARIN', 'Mandarin'), ('HINDI', 'Hindi')], max_length=20)),
                ('currency', models.CharField(choices=[('USD', 'U.S. Dollar'), ('CAD', 'Canadian Dollar'), ('EUR', 'European Euro'), ('GBP', 'British Pound'), ('CHF', 'Swiss Franc')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('geolocation', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geolocation.provider')),
            ],
        ),
    ]
